keywords_roles = {
    'data scientist': ['machine learning', 'ml', 'deep learning', 'dl', 'python', 'data analysis', 'tensorflow', 'keras', 'pytorch', 'data mining', 'statistics', 'ai', 'artificial intelligence', 'data visualization'],
    'web developer': ['html', 'css', 'javascript', 'js', 'react', 'react.js', 'node.js', 'node', 'php', 'web development', 'frontend', 'backend', 'express.js', 'next.js', 'redux'],
    'android developer': ['android', 'kotlin', 'java', 'android studio', 'android development', 'mobile development'],
    'software engineer': ['c++', 'java', 'software development', 'object-oriented programming', 'oop', 'system design', 'software engineering'],
    'cloud engineer': ['aws', 'amazon web services', 'azure', 'cloud computing', 'gcp', 'google cloud platform', 'docker', 'kubernetes', 'devops', 'cloud architecture'],
    'cybersecurity specialist': ['cybersecurity', 'penetration testing', 'pentesting', 'vulnerability assessment', 'network security', 'ethical hacking', 'information security'],
    'data engineer': ['big data', 'spark', 'hadoop', 'etl', 'airflow', 'data pipelines', 'data warehousing'],
    'ui/ux designer': ['figma', 'adobe xd', 'user interface', 'user experience', 'prototyping', 'wireframing', 'sketch'],
    'game developer': ['unity', 'unreal engine', 'game development', 'c#', '3d modeling', 'blender'],
    'blockchain developer': ['blockchain', 'ethereum', 'smart contracts', 'solidity', 'dapps', 'web3', 'nft'],
    'ai engineer': ['artificial intelligence', 'ai', 'machine learning', 'ml', 'deep learning', 'dl', 'natural language processing', 'nlp', 'computer vision'],
    'mobile app developer': ['android', 'ios', 'react native', 'flutter', 'swift', 'kotlin'],
    'database administrator': ['sql', 'mysql', 'oracle', 'postgresql', 'nosql', 'mongodb', 'database management'],
    'network engineer': ['networking', 'cisco', 'ccna', 'network security', 'routing', 'switching', 'firewall'],
    'business analyst': ['business analysis', 'requirements gathering', 'stakeholder management', 'wireframing', 'data analysis', 'jira'],
    'product manager': ['product management', 'roadmap', 'agile', 'scrum', 'product strategy', 'user research'],
    'devops engineer': ['devops', 'jenkins', 'docker', 'kubernetes', 'ansible', 'terraform', 'cicd'],
    'embedded systems engineer': ['embedded systems', 'microcontrollers', 'arduino', 'raspberry pi', 'iot', 'firmware'],
    'iot developer': ['internet of things', 'iot', 'arduino', 'raspberry pi', 'sensors', 'mqtt'],
    'robotics engineer': ['robotics', 'ros', 'robot operating system', 'sensors', 'automation', 'mechatronics'],
    'qa engineer': ['quality assurance', 'software testing', 'manual testing', 'automation testing', 'selenium', 'jira'],
    'full stack developer': ['frontend', 'backend', 'mern stack', 'mean stack', 'fullstack development', 'react', 'node.js', 'express.js', 'mongodb'],
    'frontend developer': ['html', 'css', 'javascript', 'react', 'angular', 'vue.js', 'frontend'],
    'backend developer': ['node.js', 'php', 'django', 'flask', 'express.js', 'backend', 'api development'],
    'machine learning engineer': ['machine learning', 'ml', 'deep learning', 'dl', 'tensorflow', 'keras', 'sklearn'],
    'natural language processing engineer': ['nlp', 'natural language processing', 'text mining', 'spacy', 'nltk'],
    'computer vision engineer': ['computer vision', 'opencv', 'cv', 'deep learning', 'cnn', 'image processing'],
    'bioinformatics scientist': ['bioinformatics', 'genomics', 'proteomics', 'r programming', 'python'],
    'quantitative analyst': ['quant', 'quantitative analysis', 'finance', 'data analysis', 'python', 'r'],
    'statistician': ['statistics', 'data analysis', 'r', 'spss', 'hypothesis testing', 'probability'],
    'mechanical engineer': ['autocad', 'solidworks', 'catia', 'ansys', 'mechanical design'],
    'civil engineer': ['autocad', 'revit', 'civil 3d', 'structural analysis', 'construction management'],
    'electrical engineer': ['plc', 'automation', 'electrical design', 'autocad electrical'],
    'electronics engineer': ['embedded systems', 'circuit design', 'pcb design', 'vlsi'],
    'artificial intelligence researcher': ['ai', 'artificial intelligence', 'ml', 'machine learning', 'dl', 'deep learning', 'reinforcement learning'],
    'cloud architect': ['aws', 'azure', 'gcp', 'cloud architecture', 'cloud computing', 'cloud security'],
    'solutions architect': ['solution architecture', 'aws', 'azure', 'system design', 'cloud computing'],
    'security analyst': ['cybersecurity', 'network security', 'siem', 'intrusion detection', 'malware analysis'],
    'information security analyst': ['information security', 'cybersecurity', 'risk assessment', 'vulnerability management'],
    'ethical hacker': ['ethical hacking', 'penetration testing', 'pentesting', 'kali linux', 'cybersecurity'],
    'blockchain architect': ['blockchain', 'ethereum', 'smart contracts', 'hyperledger', 'distributed ledger'],
    'system administrator': ['linux', 'windows server', 'active directory', 'system administration', 'bash'],
    'it support specialist': ['technical support', 'troubleshooting', 'hardware support', 'customer support', 'helpdesk'],
    'technical writer': ['documentation', 'technical writing', 'user manuals', 'api documentation', 'content writing'],
    'crm developer': ['salesforce', 'crm', 'dynamics 365', 'crm development'],
    'sap consultant': ['sap', 'sap hana', 'sap fico', 'sap abap'],
    'marketing analyst': ['marketing analytics', 'google analytics', 'seo', 'sem', 'marketing research'],
    'seo specialist': ['seo', 'search engine optimization', 'semrush', 'ahrefs', 'content marketing'],
    'content writer': ['content writing', 'copywriting', 'blog writing', 'creative writing'],
    'graphic designer': ['photoshop', 'illustrator', 'figma', 'adobe creative suite', 'graphic design'],
    'video editor': ['adobe premiere pro', 'after effects', 'final cut pro', 'video editing', 'cinematography'],
    'data analyst': ['data analysis', 'excel', 'sql', 'tableau', 'power bi', 'python'],
    'research scientist': ['research', 'data analysis', 'machine learning', 'scientific writing'],
    'operations manager': ['operations management', 'supply chain management', 'logistics', 'process optimization'],
    'hr specialist': ['recruitment', 'talent acquisition', 'human resources', 'onboarding', 'employee engagement'],
    'business development manager': ['business development', 'sales', 'lead generation', 'client acquisition'],
    'finance analyst': ['financial analysis', 'accounting', 'excel', 'budgeting', 'forecasting'],'data scientist': ['machine learning', 'ml', 'deep learning', 'dl', 'python', 'data analysis', 'tensorflow', 'keras', 'pytorch', 'data mining', 'statistics', 'ai', 'artificial intelligence', 'data visualization'],
    'web developer': ['html', 'css', 'javascript', 'js', 'react', 'react.js', 'node.js', 'node', 'php', 'web development', 'frontend', 'backend', 'express.js', 'next.js', 'redux'],
    'android developer': ['android', 'kotlin', 'java', 'android studio', 'android development', 'mobile development'],
    'software engineer': ['c++', 'java', 'software development', 'object-oriented programming', 'oop', 'system design', 'software engineering'],
    'cloud engineer': ['aws', 'amazon web services', 'azure', 'cloud computing', 'gcp', 'google cloud platform', 'docker', 'kubernetes', 'devops', 'cloud architecture'],
    'cybersecurity specialist': ['cybersecurity', 'penetration testing', 'pentesting', 'vulnerability assessment', 'network security', 'ethical hacking', 'information security'],
    'data engineer': ['big data', 'spark', 'hadoop', 'etl', 'airflow', 'data pipelines', 'data warehousing'],
    'ui/ux designer': ['figma', 'adobe xd', 'user interface', 'user experience', 'prototyping', 'wireframing', 'sketch'],
    'game developer': ['unity', 'unreal engine', 'game development', 'c#', '3d modeling', 'blender'],
    'blockchain developer': ['blockchain', 'ethereum', 'smart contracts', 'solidity', 'dapps', 'web3', 'nft'],
    'ai engineer': ['artificial intelligence', 'ai', 'machine learning', 'ml', 'deep learning', 'dl', 'natural language processing', 'nlp', 'computer vision'],
    'mobile app developer': ['android', 'ios', 'react native', 'flutter', 'swift', 'kotlin'],
    'database administrator': ['sql', 'mysql', 'oracle', 'postgresql', 'nosql', 'mongodb', 'database management'],
    'network engineer': ['networking', 'cisco', 'ccna', 'network security', 'routing', 'switching', 'firewall'],
    'business analyst': ['business analysis', 'requirements gathering', 'stakeholder management', 'wireframing', 'data analysis', 'jira'],
    'product manager': ['product management', 'roadmap', 'agile', 'scrum', 'product strategy', 'user research'],
    'devops engineer': ['devops', 'jenkins', 'docker', 'kubernetes', 'ansible', 'terraform', 'cicd'],
    'embedded systems engineer': ['embedded systems', 'microcontrollers', 'arduino', 'raspberry pi', 'iot', 'firmware'],
    'iot developer': ['internet of things', 'iot', 'arduino', 'raspberry pi', 'sensors', 'mqtt'],
    'robotics engineer': ['robotics', 'ros', 'robot operating system', 'sensors', 'automation', 'mechatronics'],
    'qa engineer': ['quality assurance', 'software testing', 'manual testing', 'automation testing', 'selenium', 'jira'],
    'full stack developer': ['frontend', 'backend', 'mern stack', 'mean stack', 'fullstack development', 'react', 'node.js', 'express.js', 'mongodb'],
    'frontend developer': ['html', 'css', 'javascript', 'react', 'angular', 'vue.js', 'frontend'],
    'backend developer': ['node.js', 'php', 'django', 'flask', 'express.js', 'backend', 'api development'],
    'machine learning engineer': ['machine learning', 'ml', 'deep learning', 'dl', 'tensorflow', 'keras', 'sklearn'],
    'natural language processing engineer': ['nlp', 'natural language processing', 'text mining', 'spacy', 'nltk'],
    'computer vision engineer': ['computer vision', 'opencv', 'cv', 'deep learning', 'cnn', 'image processing'],
    'bioinformatics scientist': ['bioinformatics', 'genomics', 'proteomics', 'r programming', 'python'],
    'quantitative analyst': ['quant', 'quantitative analysis', 'finance', 'data analysis', 'python', 'r'],
    'statistician': ['statistics', 'data analysis', 'r', 'spss', 'hypothesis testing', 'probability'],
    'mechanical engineer': ['autocad', 'solidworks', 'catia', 'ansys', 'mechanical design'],
    'civil engineer': ['autocad', 'revit', 'civil 3d', 'structural analysis', 'construction management'],
    'electrical engineer': ['plc', 'automation', 'electrical design', 'autocad electrical'],
    'electronics engineer': ['embedded systems', 'circuit design', 'pcb design', 'vlsi'],
    'artificial intelligence researcher': ['ai', 'artificial intelligence', 'ml', 'machine learning', 'dl', 'deep learning', 'reinforcement learning'],
    'cloud architect': ['aws', 'azure', 'gcp', 'cloud architecture', 'cloud computing', 'cloud security'],
    'solutions architect': ['solution architecture', 'aws', 'azure', 'system design', 'cloud computing'],
    'security analyst': ['cybersecurity', 'network security', 'siem', 'intrusion detection', 'malware analysis'],
    'information security analyst': ['information security', 'cybersecurity', 'risk assessment', 'vulnerability management'],
    'ethical hacker': ['ethical hacking', 'penetration testing', 'pentesting', 'kali linux', 'cybersecurity'],
    'blockchain architect': ['blockchain', 'ethereum', 'smart contracts', 'hyperledger', 'distributed ledger'],
    'system administrator': ['linux', 'windows server', 'active directory', 'system administration', 'bash'],
    'it support specialist': ['technical support', 'troubleshooting', 'hardware support', 'customer support', 'helpdesk'],
    'technical writer': ['documentation', 'technical writing', 'user manuals', 'api documentation', 'content writing'],
    'crm developer': ['salesforce', 'crm', 'dynamics 365', 'crm development'],
    'sap consultant': ['sap', 'sap hana', 'sap fico', 'sap abap'],
    'marketing analyst': ['marketing analytics', 'google analytics', 'seo', 'sem', 'marketing research'],
    'seo specialist': ['seo', 'search engine optimization', 'semrush', 'ahrefs', 'content marketing'],
    'content writer': ['content writing', 'copywriting', 'blog writing', 'creative writing'],
    'graphic designer': ['photoshop', 'illustrator', 'figma', 'adobe creative suite', 'graphic design'],
    'video editor': ['adobe premiere pro', 'after effects', 'final cut pro', 'video editing', 'cinematography'],
    'data analyst': ['data analysis', 'excel', 'sql', 'tableau', 'power bi', 'python'],
    'research scientist': ['research', 'data analysis', 'machine learning', 'scientific writing'],
    'operations manager': ['operations management', 'supply chain management', 'logistics', 'process optimization'],
    'hr specialist': ['recruitment', 'talent acquisition', 'human resources', 'onboarding', 'employee engagement'],
    'business development manager': ['business development', 'sales', 'lead generation', 'client acquisition'],
    'finance analyst': ['financial analysis', 'accounting', 'excel', 'budgeting', 'forecasting'],
}